import './globals.css'
import {  Open_Sans } from 'next/font/google'
import { ClerkProvider  } from '@clerk/nextjs'
import GlobalHeader from '../components/global-components/global-header'
const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Parks and Pools',
  description: 'Generated by create next app',
}

function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`bg-slate-50 min-h-screen flex flex-col ${openSans.className}`}>
          <GlobalHeader />
          <div>
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}


export default RootLayout;